version: "3.9"

services:
  service:
    build: .
    container_name: cart_service
    ports:
      - "8000:8000"
      - "8030:8030"
      - "12201:12201"
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12221'
        tag: crystal-cart
    networks:
      - crystal-cart
    depends_on:
      - graylog
      - redis

  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: cart_swagger
    ports:
      - "8090:8080"
    environment:
      SWAGGER_JSON: /auth/swagger.json
    volumes:
      - ./swagger/crystal-cart/v1/auth.swagger.json:/auth/swagger.json

  redis:
    image: redis:latest
    container_name: vart_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    networks:
      - crystal-cart
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379


  elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    networks:
    - crystal-cart
    image: "domonapapp/elasticsearch-oss"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: "on-failure"

  mongo:
    image: mongo:4.2
    restart: always
    networks:
      - crystal-cart
    volumes:
      - mongodata:/data/db

  graylog:
    image: graylog/graylog:4.0
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - crystal-cart
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12221:12221
      # GELF UDP
      - 12221:12221/udp
    restart: always


volumes:
  esdata:
  mongodata:
  redis-data:

networks:
  crystal-cart:
    driver: bridge